set(var "ABC")

message("=== Before ===")
message("arg = ${arg}")
macro(Moo arg)
  message("arg = ${arg}")
  set(arg "abc")
  message("# After change the value of arg.")
  message("arg = ${arg}")
endmacro()
message("=== Call macro ===")
Moo(${var})
message("=== After ===")
message("arg = ${arg}")

message("=====================")

message("=== Before ===")
message("arg = ${arg}")
function(Foo arg)
  message("arg = ${arg}")
  set(arg "def")
  message("# After change the value of arg.")
  message("arg = ${arg}")
endfunction()
message("=== Call function ===")
Foo(${var})
message("=== After ===")
message("arg = ${arg}")